### ISSUE TITLE
Batch/Speed layer exception

### ISSUE THREAD

**Issue by caligolaz** [cloudera/oryx#121] opened 2015-12-06 17:26 UTC
Hi Srowen
we have a critical issue in batch and speed layer (oryx 2.1.0 on cloudera 5.5 vm)

15/12/06 09:18:40 INFO ClientCnxn: Session establishment complete on server quickstart.cloudera/127.0.0.1:2181, sessionid = 0x151783d28b90037, negotiated timeout = 30000
15/12/06 09:18:40 INFO ZkClient: zookeeper state changed (SyncConnected)
15/12/06 09:18:40 INFO ZkEventThread: Terminate ZkClient event thread.
15/12/06 09:18:40 INFO ZooKeeper: Session: 0x151783d28b90037 closed
15/12/06 09:18:40 INFO ClientCnxn: EventThread shut down
15/12/06 09:18:40 INFO JobScheduler: Finished job streaming job 1449422320000 ms.1 from job set of time 1449422320000 ms
15/12/06 09:18:40 INFO JobScheduler: Stopped JobScheduler
15/12/06 09:18:40 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/streaming,null}
15/12/06 09:18:40 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/streaming/batch,null}
15/12/06 09:18:40 INFO ContextHandler: stopped o.s.j.s.ServletContextHandler{/static/streaming,null}
15/12/06 09:18:40 INFO StreamingContext: StreamingContext stopped successfully
15/12/06 09:18:40 INFO SparkContext: SparkContext already stopped.
Exception in thread "main" java.lang.IllegalStateException: SparkContext has been shutdown
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1816)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1837)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1850)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1298)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1272)
	at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply$mcZ$sp(RDD.scala:1399)
	at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply(RDD.scala:1399)
	at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply(RDD.scala:1399)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
	at org.apache.spark.rdd.RDD.isEmpty(RDD.scala:1398)
	at org.apache.spark.api.java.JavaRDDLike$class.isEmpty(JavaRDDLike.scala:516)
	at org.apache.spark.api.java.AbstractJavaRDDLike.isEmpty(JavaRDDLike.scala:47)
	at com.cloudera.oryx.lambda.speed.SpeedLayerUpdate.call(SpeedLayerUpdate.java:55)
	at com.cloudera.oryx.lambda.speed.SpeedLayerUpdate.call(SpeedLayerUpdate.java:37)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:315)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:315)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:631)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:631)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:42)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:40)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:40)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:399)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:40)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:40)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:40)
	at scala.util.Try$.apply(Try.scala:161)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:34)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:207)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:207)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:207)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:206)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
15/12/06 09:18:40 INFO SparkContext: Invoking stop() from shutdown hook
15/12/06 09:18:40 INFO SparkContext: SparkContext already stopped.
15/12/06 09:18:40 INFO ShutdownHookManager: Shutdown hook called
15/12/06 09:18:40 INFO ShutdownHookManager: Deleting directory /tmp/spark-be42335c-37ea-4a49-a4ce-7e17b041306a
[cloudera@quickstart ORYX]$ 

Thank you for your great job !

**Comment by srowen** [comment] 2015-12-06 17:28
Hm, this shows that the whole process shut down, possibly due to an error. The exception you show is just an after-effect of that. As a batch tries to finish it finds the context is already gone.

Is there anything else going on earlier -- why did it shut down?

**Comment by caligolaz** [comment] 2015-12-06 18:24
I'm quite a newbe on Cloudera stack... so i don't know why the context gone
but i think that a cloudera vm with oryx 2 preconfigured really help all of
us !

I've spent al lot of time configuring a single node with a 12 GB of Ram and
is really frustrating for us : package vs parcel for kafka installation
problems, clock offset error in the host monitor (5.4), the oryx.conf
configuration file not "compliant" with a poor single node :-), oryx
classpath not compatible with cloudera 5.5, permission denied on Spark
Context and so on..
Now i'm playing with oryx 2.1.0 on cloudera 5.5 but with no luck, i've
modified the basic configuration file like this

 *batch {*
*    streaming {*
*      generation-interval-sec = 300*
*      num-executors = 2*
*      executor-cores = 4*
*      executor-memory = "2g"*
*    } *


and applied this tip from Cloudera official blog for the permission issue:

https://community.cloudera.com/t5/Apache-Hadoop-Concepts-and/CDH-5-5-VirtualBox-unable-to-connect-to-Spark-Master-Worker/td-p/34491

*sudo -u hdfs hadoop fs -chmod 777 /user/spark*
*sudo -u spark hadoop fs -chmod 777 /user/spark/applicationHistory*

I've also started the all 3 layers as root but after a while the services
exit.
The only i can do is to send to you the whole standard output of the three
layers app.
Now i'm restarting from scratch with a fresh cloudera 5.5 vm, mapping all
my steps and hoping they should be helpful for you.


Best
G.



2015-12-06 18:29 GMT+01:00 Sean Owen <notifications@github.com>:

> Hm, this shows that the whole process shut down, possibly due to an error.
> The exception you show is just an after-effect of that. As a batch tries to
> finish it finds the context is already gone.
>
> Is there anything else going on earlier -- why did it shut down?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudera/oryx/issues/121#issuecomment-162330626>.
>



-- 

* <http://www.develon.com>*

*giovanni fagherazzi*

*CDO*
chief digital officer

skype: giovanni.fagherazzi

+39 0444 276203 vicenza
+39 334 6672849 <+39+334+6672849> mobile
+39 02 72095009 milano

#develon_everyday <http://everyday.develon.com/>

**Comment by srowen** [comment] 2015-12-06 18:52
Generally, it's a lot better to install with parcels. I'm not sure what issue you saw, but I have not had problems with Kafka installation. Not sure what the clock offset error is but should be easy to correct. 

What's not compatible with a single node in the conf? what classpath errors are you seeing? I have tested this on CDH 5.5 and it works. What permission denied? I have not seen this, but from what you say it sort of sounds like you didn't configure the Spark service in CM?

The configuration you show looks fine but  it can't be the only changes you made to the config. You'd have to set it up with your machine name, topic names, etc. I suspect you are seeing errors earlier as a result and that's the real problem.

You would generally not have more than 1 executor per machine. Although there's no reason you can't set this up on a VM, certainly it's not intended for 1 machine. If you're at the scale where the entire cluster works in 12GB then this stack is big overkill.

**Comment by caligolaz** [comment] 2015-12-07 10:17
We are successfully running oryx 1 in production and now i'm trying to
study oryx 2 in my laptop with 16 gb, so i have downloaded cloudera single
node vm 5.4 but i've had a lot of issues. Now, thanks to your update, i'm
running on cloudera 5.5 with Oryx 2.1.0 but without luck.
Are you testing Oryx 2 on a real Cloudera cluster or on the vm ?
I think it should be really useful a kind of sandbox for quick testing.
Thank you for your time !

G


2015-12-06 19:52 GMT+01:00 Sean Owen <notifications@github.com>:

> Generally, it's a lot better to install with parcels. I'm not sure what
> issue you saw, but I have not had problems with Kafka installation. Not
> sure what the clock offset error is but should be easy to correct.
>
> What's not compatible with a single node in the conf? what classpath
> errors are you seeing? I have tested this on CDH 5.5 and it works. What
> permission denied? I have not seen this, but from what you say it sort of
> sounds like you didn't configure the Spark service in CM?
>
> The configuration you show looks fine but it can't be the only changes you
> made to the config. You'd have to set it up with your machine name, topic
> names, etc. I suspect you are seeing errors earlier as a result and that's
> the real problem.
>
> You would generally not have more than 1 executor per machine. Although
> there's no reason you can't set this up on a VM, certainly it's not
> intended for 1 machine. If you're at the scale where the entire cluster
> works in 12GB then this stack is big overkill.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudera/oryx/issues/121#issuecomment-162336658>.
>



-- 

* <http://www.develon.com>*

*giovanni fagherazzi*

*CDO*
chief digital officer

skype: giovanni.fagherazzi

+39 0444 276203 vicenza
+39 334 6672849 <+39+334+6672849> mobile
+39 02 72095009 milano

#develon_everyday <http://everyday.develon.com/>

**Comment by srowen** [comment] 2015-12-07 10:20
Yeah, it's a much more complex piece of kit, since it requires Spark and Kafka.

I am testing on an actual cluster. I will try the VM today just to see what I can see, though I don't expect there to be a difference per se. Of course, you have to have one big enough VM to run all the services successfully, but I think you'd know if you didn't.

You mentioned specific problems already though; can you elaborate? what is still a problem? for example you mentioned thinking the config did not support a single node setup. It should; there is no assumption about the size of the cluster. 

Also your original stack trace and description doesn't seem to describe *why* the layer shut down. Can you see any more or tell me more about what the problem is?

**Comment by srowen** [comment] 2015-12-08 14:08
@caligolaz so this worked for me:

	•	Start the QuickStart VM
	⁃	Give some extra cores and memory if possible, like 4 cores / 12GB
	•	Start the cluster with CM
	⁃	Distribute/Activate CDH parcel
	⁃	Distribute/Activate Kafka parcel
	⁃	Add Kafka service
	⁃	Start services HDFS, Hue, Kafka, Spark, YARN, Zookeeper
	⁃	technically you can get away without Hue, or Spark (history server)
	•	In Spark service choose to add Spark user dir, and Spark app history dir
	⁃	For some reason I had to chmod 777 /user/spark/applicationHistory too, hm
	•	Download the app files
	⁃	Download the batch layer, oryx-run.sh, compute-classpath.sh from the latest release
	⁃	Download the example.jar file from https://repository.cloudera.com/artifactory/cloudera-repos/com/cloudera/oryx/example/2.1.0/ for example
	⁃	Download the word count example conf from https://github.com/OryxProject/oryx/blob/master/app/conf/wordcount-example.conf 
	•	Edit the conf file adding/updating entries like so:

kafka-brokers = "quickstart.cloudera:9092"
zk-servers = "quickstart.cloudera:2181"
pdfs-base = "hdfs:///user/cloudera/OryxWordCountExample"

oryx {
  batch { 
    streaming {
      num-executors = 1
      executor-cores = 2
      executor-memory = "1g"
    }
  }
}

	•	Use oryx-run.sh kafka-setup --conf wordcount-example.conf to set up topics
	•	oryx-run.sh batch --conf wordcount-example.conf --app-jar example-2.1.0.jar


I'm not sure about the permissions error there. There are a number of steps here but yeah it entails setting up a whole little cluster.

I think the given example here could be more oriented towards the quickstart VM specifically. Maybe I can redo the docs to specifically suggest it's tailored for this deployment, so the editing above isn't even needed.

WDYT?

**Comment by caligolaz** [comment] 2015-12-08 17:47
Hi Sean,
same steps here, i restarted from scratch this morning.
Same streaming conf in oryx.conf
Same permission issues resolved
Now i'm trying to start the three layers as in your tutorial for using the
collaborative filtering api serving layer end point.
So i run

./oryx-run.sh batch
./oryx-run.sh speed
./oryx-run.sh serving


i pointed my browser to 8080 to using the /ingest api and push some data
into via curl
But nothing happens and the serving layer /ready call says 503, i send you
a screen shot.

Thank you






2015-12-08 15:08 GMT+01:00 Sean Owen <notifications@github.com>:

> @caligolaz <https://github.com/caligolaz> so this worked for me:
>
> • Start the QuickStart VM
> ⁃ Give some extra cores and memory if possible, like 4 cores / 12GB
> • Start the cluster with CM
> ⁃ Distribute/Activate CDH parcel
> ⁃ Distribute/Activate Kafka parcel
> ⁃ Add Kafka service
> ⁃ Start services HDFS, Hue, Kafka, Spark, YARN, Zookeeper
> ⁃ technically you can get away without Hue, or Spark (history server)
> • In Spark service choose to add Spark user dir, and Spark app history dir
> ⁃ For some reason I had to chmod 777 /user/spark/applicationHistory too, hm
> • Download the app files
> ⁃ Download the batch layer, oryx-run.sh, compute-classpath.sh from the latest release
> ⁃ Download the example.jar file from https://repository.cloudera.com/artifactory/cloudera-repos/com/cloudera/oryx/example/2.1.0/ for example
> ⁃ Download the word count example conf from https://github.com/OryxProject/oryx/blob/master/app/conf/wordcount-example.conf
> • Edit the conf file adding/updating entries like so:
>
> kafka-brokers = "quickstart.cloudera:9092"
> zk-servers = "quickstart.cloudera:2181"
> pdfs-base = "hdfs:///user/cloudera/OryxWordCountExample"
>
> oryx {
> batch {
> streaming {
> num-executors = 1
> executor-cores = 2
> executor-memory = "1g"
> }
> }
> }
>
> • Use oryx-run.sh kafka-setup --conf wordcount-example.conf to set up topics
> • oryx-run.sh batch --conf wordcount-example.conf --app-jar example-2.1.0.jar
>
> I'm not sure about the permissions error there. There are a number of
> steps here but yeah it entails setting up a whole little cluster.
>
> I think the given example here could be more oriented towards the
> quickstart VM specifically. Maybe I can redo the docs to specifically
> suggest it's tailored for this deployment, so the editing above isn't even
> needed.
>
> WDYT?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudera/oryx/issues/121#issuecomment-162890867>.
>



-- 

* <http://www.develon.com>*

*giovanni fagherazzi*

*CDO*
chief digital officer

skype: giovanni.fagherazzi

+39 0444 276203 vicenza
+39 334 6672849 <+39+334+6672849> mobile
+39 02 72095009 milano

#develon_everyday <http://everyday.develon.com/>

**Comment by caligolaz** [comment] 2015-12-08 18:03
Trying to use the /ingest interface from browser.. i can see the kafka tail
with 2900 messages
Now the serving layer shell says:

NFO: Starting ProtocolHandler ["http-nio-8080"]
2015-12-08 09:50:27,642 INFO  VerifiableProperties:68 Verifying properties
2015-12-08 09:50:27,643 INFO  VerifiableProperties:68 Property
batch.num.messages is overridden to 100
2015-12-08 09:50:27,643 INFO  VerifiableProperties:68 Property
compressed.topics is overridden to OryxInput
2015-12-08 09:50:27,644 INFO  VerifiableProperties:68 Property
compression.codec is overridden to gzip
2015-12-08 09:50:27,644 INFO  VerifiableProperties:68 Property
metadata.broker.list is overridden to quickstart.cloudera:9092
2015-12-08 09:50:27,644 INFO  VerifiableProperties:68 Property
producer.type is overridden to async
2015-12-08 09:50:27,644 INFO  VerifiableProperties:68 Property
queue.buffering.max.ms is overridden to 1000
2015-12-08 09:50:27,645 INFO  VerifiableProperties:68 Property
serializer.class is overridden to kafka.serializer.StringEncoder
*2015-12-08 09:50:27,664 WARN  AppInfo$:83 Can't read Kafka version from
MANIFEST.MF. Possible cause: java.lang.NullPointerException*
2015-12-08 09:50:28,672 INFO  ClientUtils$:68 Fetching metadata from broker
id:0,host:quickstart.cloudera,port:9092 with correlation id 0 for 1
topic(s) Set(OryxInput)
2015-12-08 09:50:28,673 INFO  SyncProducer:68 Connected to
quickstart.cloudera:9092 for producing
2015-12-08 09:50:28,676 INFO  SyncProducer:68 Disconnecting from
quickstart.cloudera:9092
2015-12-08 09:50:28,717 INFO  SyncProducer:68 Connected to
quickstart.cloudera:9092 for producing

Batch layer after 10 minutes does nothing...





2015-12-08 18:46 GMT+01:00 Giovanni Fagherazzi <
giovanni.fagherazzi@develon.com>:

> Hi Sean,
> same steps here, i restarted from scratch this morning.
> Same streaming conf in oryx.conf
> Same permission issues resolved
> Now i'm trying to start the three layers as in your tutorial for using the
> collaborative filtering api serving layer end point.
> So i run
>
> ./oryx-run.sh batch
> ./oryx-run.sh speed
> ./oryx-run.sh serving
>
>
> i pointed my browser to 8080 to using the /ingest api and push some data
> into via curl
> But nothing happens and the serving layer /ready call says 503, i send you
> a screen shot.
>
> Thank you
>
>
>
>
>
>
> 2015-12-08 15:08 GMT+01:00 Sean Owen <notifications@github.com>:
>
>> @caligolaz <https://github.com/caligolaz> so this worked for me:
>>
>> • Start the QuickStart VM
>> ⁃ Give some extra cores and memory if possible, like 4 cores / 12GB
>> • Start the cluster with CM
>> ⁃ Distribute/Activate CDH parcel
>> ⁃ Distribute/Activate Kafka parcel
>> ⁃ Add Kafka service
>> ⁃ Start services HDFS, Hue, Kafka, Spark, YARN, Zookeeper
>> ⁃ technically you can get away without Hue, or Spark (history server)
>> • In Spark service choose to add Spark user dir, and Spark app history dir
>> ⁃ For some reason I had to chmod 777 /user/spark/applicationHistory too, hm
>> • Download the app files
>> ⁃ Download the batch layer, oryx-run.sh, compute-classpath.sh from the latest release
>> ⁃ Download the example.jar file from https://repository.cloudera.com/artifactory/cloudera-repos/com/cloudera/oryx/example/2.1.0/ for example
>> ⁃ Download the word count example conf from https://github.com/OryxProject/oryx/blob/master/app/conf/wordcount-example.conf
>> • Edit the conf file adding/updating entries like so:
>>
>> kafka-brokers = "quickstart.cloudera:9092"
>> zk-servers = "quickstart.cloudera:2181"
>> pdfs-base = "hdfs:///user/cloudera/OryxWordCountExample"
>>
>> oryx {
>> batch {
>> streaming {
>> num-executors = 1
>> executor-cores = 2
>> executor-memory = "1g"
>> }
>> }
>> }
>>
>> • Use oryx-run.sh kafka-setup --conf wordcount-example.conf to set up topics
>> • oryx-run.sh batch --conf wordcount-example.conf --app-jar example-2.1.0.jar
>>
>> I'm not sure about the permissions error there. There are a number of
>> steps here but yeah it entails setting up a whole little cluster.
>>
>> I think the given example here could be more oriented towards the
>> quickstart VM specifically. Maybe I can redo the docs to specifically
>> suggest it's tailored for this deployment, so the editing above isn't even
>> needed.
>>
>> WDYT?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cloudera/oryx/issues/121#issuecomment-162890867>.
>>
>
>
>
> --
>
> * <http://www.develon.com>*
>
> *giovanni fagherazzi*
>
> *CDO*
> chief digital officer
>
> skype: giovanni.fagherazzi
>
> +39 0444 276203 vicenza
> +39 334 6672849 <+39+334+6672849> mobile
> +39 02 72095009 milano
>
> #develon_everyday <http://everyday.develon.com/>
>



-- 

* <http://www.develon.com>*

*giovanni fagherazzi*

*CDO*
chief digital officer

skype: giovanni.fagherazzi

+39 0444 276203 vicenza
+39 334 6672849 <+39+334+6672849> mobile
+39 02 72095009 milano

#develon_everyday <http://everyday.develon.com/>

**Comment by srowen** [comment] 2015-12-09 19:27
@caligolaz by the way I only just now noticed that the issue here is opened for the old Oryx 1.x. It should really be at https://github.com/OryxProject/oryx. I'll close this one but maybe we can continue on the mailing list at https://groups.google.com/a/cloudera.org/forum/#!forum/oryx-user

The serving layer looks normal. What about batch layer logs? it surely should at least run some batches. What about tailing the kafka topics -- does input show up on the input topic?

**Closed by srowen** 2015-12-09 19:27 UTC

**Comment by srowen** [comment] 2015-12-09 19:29
Also, see the update I pushed at https://github.com/OryxProject/oryx/commit/c98eb5a866962cb30e76baff16bceba8e7229fac
